INSERT INTO "Players"."Player"
(name, lastname, age, position, goalsNumber, team)
VALUES
    ('David','Alaba',33,'DEF',0,'Real Madrid'),
    ('Ronald','Araujo',26,'DEF',1,'FC Barcelona'),
    ('César','Azpilicueta',35,'DEF',0,'Atlético de Madrid'),
    ('Pablo','Barrios',22,'MF',2,'Atlético de Madrid'),
    ('Jude','Bellingham',21,'MF',19,'Real Madrid'),
    ('Raphinha','Belloli',28,'FWD',6,'FC Barcelona'),
    ('Eduardo','Camavinga',22,'MF',2,'Real Madrid'),
    ('Dani','Carvajal',33,'DEF',1,'Real Madrid'),
    ('Andreas','Christensen',29,'DEF',1,'FC Barcelona'),
    ('Ángel','Correa',30,'FWD',6,'Atlético de Madrid'),
    ('Thibaut','Courtois',33,'GK',0,'Real Madrid'),
    ('Pau','Cubarsí',18,'DEF',0,'FC Barcelona'),
    ('Brahim','Díaz',25,'MF',6,'Real Madrid'),
    ('Gavi','Gavi',20,'MF',2,'FC Barcelona'),
    ('José María','Giménez',30,'DEF',1,'Atlético de Madrid'),
    ('Rodrygo','Goes',24,'FWD',10,'Real Madrid'),
    ('Pedri','González',22,'MF',3,'FC Barcelona'),
    ('Antoine','Griezmann',34,'FWD',16,'Atlético de Madrid'),
    ('İlkay','Gündoğan',34,'MF',5,'FC Barcelona'),
    ('Vinícius','Júnior',25,'FWD',15,'Real Madrid'),
    ('Jules','Koundé',26,'DEF',1,'FC Barcelona'),
    ('Robin','Le Normand',28,'DEF',1,'Atlético de Madrid'),
    ('Robert','Lewandowski',36,'FWD',19,'FC Barcelona'),
    ('Samuel','Lino',25,'FWD',7,'Atlético de Madrid'),
    ('Marcos','Llorente',30,'MF',6,'Atlético de Madrid'),
    ('Andriy','Lunin',26,'GK',0,'Real Madrid'),
    ('Fermín','López',22,'MF',5,'FC Barcelona'),
    ('Reinildo','Mandava',31,'DEF',0,'Atlético de Madrid'),
    ('Kylian','Mbappé',26,'FWD',21,'Real Madrid'),
    ('Ferland','Mendy',30,'DEF',1,'FC Barcelona'),
    ('Éder','Militão',27,'DEF',1,'Real Madrid'),
    ('Nahuel','Molina',27,'DEF',2,'Atlético de Madrid'),
    ('Álvaro','Morata',32,'FWD',15,'Atlético de Madrid'),
    ('Endrick','Moreira',19,'FWD',6,'Real Madrid'),
    ('Juan','Musso',31,'GK',0,'Atlético de Madrid'),
    ('Jan','Oblak',32,'GK',0,'Atlético de Madrid'),
    ('Iñaki','Peña',26,'GK',0,'FC Barcelona'),
    ('Koke','Resurrección',33,'MF',1,'Atlético de Madrid'),
    ('Antonio','Rüdiger',32,'DEF',2,'Real Madrid'),
    ('Aurélien','Tchouaméni',25,'MF',3,'Real Madrid'),
    ('Ferran','Torres',25,'FWD',8,'FC Barcelona'),
    ('Federico','Valverde',27,'MF',4,'Real Madrid'),
    ('Lamine','Yamal',17,'FWD',7,'FC Barcelona'),
    ('Frenkie','de Jong',28,'MF',2,'FC Barcelona'),
    ('Rodrigo','de Paul',31,'MF',3,'Atlético de Madrid'),
    ('Marc-André','ter Stegen',33,'GK',0,'FC Barcelona'),
    ('Saúl','Ñíguez',30,'MF',3,'Atlético de Madrid');
